platform :ios, '7.0'

pod 'Facebook-iOS-SDK'
pod 'JASidePanels', '~> 1.3.2'
pod 'SDWebImage'
pod 'SVProgressHUD', :head
pod 'AFNetworking', '~> 2.0'
pod 'Reachability'
pod 'DateTools'
pod 'MCSwipeTableViewCell'
pod 'NKOColorPickerView'
pod 'SVPullToRefresh'
pod 'EXPhotoViewer'
pod 'MHCustomTabBarController'
pod 'UzysAssetsPickerController', :git => 'https://github.com/meitianapp/UzysAssetsPickerController.git', :commit => 'aa853fe406e88ab1ccf7af40f1f71857cef8da18'
pod 'TOCropViewController'
pod 'CocoaLumberjack', '~> 1.9'
pod 'SVGKit'